--- 
title: "Macroecological relationships between primary productivity and ecological specialisation"
author: "Hugh Burley"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Abstract

\


A key debate in contemporary ecology concerns whether ecosystem functions such as productivity are distinctly influenced by biological diversity in natural environments. Recent work has emphasised the importance of links between ecosystem functions and measures of ecological specialisation as proxies of biodiversity. However, few studies have analysed these relationships at broad spatio-temporal scales. This research tests the empirical relationship between primary productivity and ecological specialisation at continental and bioregional scales, using two proxies of specialisation: taxonomic β-diversity and site-level environmental niche width. It also examines how the environmental niches of species vary across continental environmental gradients. 

\

Gross primary productivity (GPP) may be influenced not only by the biological diversity at each location (α-diversity) but also by the biological turnover between locations (β-diversity). Generalized additive models were used to test whether the magnitude or variability of GPP were distinctly influenced by either taxonomic α- or β-diversity across continental Australia, over and above environmental influences. Neither α- nor β-diversity improved the explanatory power of GPP models beyond that of environment-only models.

\

The realised environmental niches of species are important indicators of ecological specialisation and biogeographic history. Bivariate regression models were used to test whether species niches vary across continental environmental gradients for 1771 vascular plants from the Australian Wet Tropics. The temperature niches of these species did not vary substantially. However, niches were narrower in drier and less fertile environments. 

\

The macroecological complementarity hypothesis predicts that locations with greater ecological specialisation —those with collectively narrower niches — should be more productive than locations with less ecological specialisation. For pairs of environmentally similar Wet Tropics sites, linear models were used to test the pairwise relationship between differences in site GPP (response) and differences in the median environmental niche width of all tree species present at each site (predictor). Sites with narrower temperature niche widths had higher productivity, whereas sites with narrower rainfall niche widths had lower productivity. These results will improve our understanding of the broad-scale interrelationships between ecosystem functions, environmental conditions and ecological specialisation in natural ecosystems, helping to assess utilitarian arguments for biodiversity conservation.

\

